services:
  api:
    container_name: sage_api_gateway
    build:
      context: ./services/api_gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./services/api_gateway:/app
      - /app/venv/  
    environment:
      - PYTHONPATH=/app
      - PATH=/app/venv/bin:$PATH
    command: /app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --reload --loop uvloop

  auth:
    container_name: sage_auth_service
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth:/app
      - /app/venv/  
      - ./services/auth/.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - PATH=/app/venv/bin:$PATH
    env_file:
      - ./services/auth/.env
    command: /app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8001 --reload --loop uvloop
    depends_on:
      auth_db:
        condition: service_healthy

  auth_db:
    container_name: sage_auth_db
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    env_file:
      - ./services/auth/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  auth_db_data:
